name: Auth API Workflow

on:
  push:
    branches: [ "ci_testing" ]
  pull_request:
    branches: [ "ci_testing" ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build the Docker image
      working-directory: auth-api
      run: docker build . --file Dockerfile --tag sample-app-auth-api:${GITHUB_REF##*/}-${GITHUB_SHA}
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
         image-ref: 'docker.io/sample-app-auth-api:${GITHUB_REF##*/}-${GITHUB_SHA}'
         format: 'sarif'
         output: 'trivy-results.sarif'
         severity: 'CRITICAL,HIGH'
         
    - name: Upload Trivy scan results to Github security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
         sarif_file: 'trivy-results.sarif' 


    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mcs-poc-001
        IMAGE_TAG: ${GITHUB_SHA}
      if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

   

    
